language: python
sudo: required
python:
  - "3.6"
  # - "3.7"
install:
  - pip install .[dev] && pip install .
script:
  - python -m unittest tests.test_createpythonpackage.StaticTests.test_static

cache:
  pip: true
  yarn: true
  directories:
    - node_modules